name: GoActions
on:
  push:
    branches:
      - master

jobs:
  local-cache:
    name: Setup local-cache version
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        go: [1.16]

    steps:
      - name: checkout codebase
        uses: actions/checkout@v2

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{matrix.go}}

      - name: ensure the go has been installed
        run: go version

      - name: run lint
        run: |
          go mod tidy
          go vet ./...
          chmod +x tools/*
          make proto && make build